// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'cep_app';

  static const String assets_images_building_app_json = 'assets/images/building_app.json';
  static const String cep_app$assets_images_building_app_json = 'packages/cep_app/assets/images/building_app.json';

  static const String assets_images_building_page_json = 'assets/images/building_page.json';
  static const String cep_app$assets_images_building_page_json = 'packages/cep_app/assets/images/building_page.json';
}
